"""Reproduce bounded offline analysis of the captured A1625 ANS DRAM image."""
from pathlib import Path
import hashlib
import json
import os
import re
import struct
import subprocess

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'artifacts/ans-offline-tests'
image = OUT / 'ans-fw-live-region.bin'
raw = image.read_bytes()
expected = '41ce142b90ce7b4fe51a4ea078dcbc6a936d19129b7f8709fcbe5a4e674a1482'
if len(raw) != 10485760 or hashlib.sha256(raw).hexdigest() != expected:
    raise ValueError('requires the exact captured A1625 image')
bindir = Path.home() / 'scoop/apps/msys2/current/ucrt64/bin'
os.environ['PATH'] = str(bindir) + os.pathsep + os.environ['PATH']
elf = OUT / 'ans-fw-live-region.elf'
subprocess.run([str(bindir / 'llvm-objcopy.exe'), '-I', 'binary', '-O',
                'elf32-littlearm', '-B', 'arm', str(image), str(elf)], check=True)
reports = []
power_table, power_count = struct.unpack_from('<II', raw, 0x4c678)
if power_count > 32 or power_table + power_count * 12 > len(raw):
    raise ValueError('invalid captured power callback table')
for name, triple, start, end in [('bootstrap', 'armv7-none-eabi', 0, 0x438),
                                ('thumb-entry', 'thumbv7-none-eabi', 0x2c20, 0x2f14),
                                ('clog-readonly-log', 'thumbv7-none-eabi', 0x120ac, 0x12140),
                                ('event-bits', 'thumbv7-none-eabi', 0x10c38, 0x10c54),
                                ('event-consume', 'thumbv7-none-eabi', 0x3b3f0, 0x3b408),
                                ('task-select', 'thumbv7-none-eabi', 0x3b4e4, 0x3b55c),
                                ('command-dispatch', 'thumbv7-none-eabi', 0x3cf6c, 0x3cfce),
                                ('write-gate', 'thumbv7-none-eabi', 0x3d1d4, 0x3d214),
                                ('identify-dispatch', 'thumbv7-none-eabi', 0x3d4d4, 0x3d512),
                                ('writable-violation', 'thumbv7-none-eabi', 0x3d650, 0x3d680),
                                ('restricted-operation-table', 'thumbv7-none-eabi', 0x36968, 0x369c0),
                                ('request-completion', 'thumbv7-none-eabi', 0x3b3b8, 0x3b3ec),
                                ('range-index-bounds', 'thumbv7-none-eabi', 0x35c80, 0x35cc0),
                                ('request-release', 'thumbv7-none-eabi', 0x3b734, 0x3b812),
                                ('tag-completion', 'thumbv7-none-eabi', 0x3d734, 0x3d7e8),
                                ('completion-wire', 'thumbv7-none-eabi', 0x3ce14, 0x3cea6),
                                ('internal-dispatch', 'thumbv7-none-eabi', 0x182ea, 0x18352),
                                ('identify-producer-inputs', 'thumbv7-none-eabi', 0x18ae8, 0x18b50),
                                ('identify-producer-stores', 'thumbv7-none-eabi', 0x19138, 0x191d6),
                                ('enable-write-host-dispatch', 'thumbv7-none-eabi', 0x3d3ae, 0x3d3c2),
                                ('enable-write-handler', 'thumbv7-none-eabi', 0x18c70, 0x18cca),
                                ('background-schedule', 'thumbv7-none-eabi', 0x2c724, 0x2c74c),
                                ('background-worker-entry', 'thumbv7-none-eabi', 0x2c760, 0x2c7c2),
                                ('background-worker-exit', 'thumbv7-none-eabi', 0x2d20a, 0x2d25c),
                                ('background-list-release', 'thumbv7-none-eabi', 0x2db78, 0x2dbd6),
                                ('background-buffer-release', 'thumbv7-none-eabi', 0x2dc68, 0x2dc96),
                                ('release-dispatch', 'thumbv7-none-eabi', 0x2db68, 0x2db78),
                                ('internal-request-release', 'thumbv7-none-eabi', 0x2e0e8, 0x2e100),
                                ('allocator-release', 'thumbv7-none-eabi', 0x32a98, 0x32b58),
                                ('allocator-wait-registration', 'thumbv7-none-eabi', 0x32b70, 0x32bdc),
                                ('bootstrap-memset', 'armv7-none-eabi', 0x1a5c, 0x1b38),
                                ('startup-init-arrays', 'thumbv7-none-eabi', 0x2f6c, 0x2f8e),
                                ('startup-main-entry', 'thumbv7-none-eabi', 0xa54c, 0xa5b0),
                                ('startup-main-mappings', 'thumbv7-none-eabi', 0xa5b0, 0xa69a),
                                ('startup-main-heap-join', 'thumbv7-none-eabi', 0xa69a, 0xa6b8),
                                ('startup-main-task-array', 'thumbv7-none-eabi', 0xa6b8, 0xa6fc),
                                ('power-task-dispatch', 'thumbv7-none-eabi', 0x9250, 0x934a),
                                ('power-task-retained-callback', 'thumbv7-none-eabi', 0x7860, 0x78b4),
                                ('power-callback-map-registration', 'thumbv7-none-eabi', 0x78c0, 0x79b4),
                                ('power-callback-map-caller', 'thumbv7-none-eabi', 0x84b0, 0x8526),
                                ('power-callback-reference-acquire', 'thumbv7-none-eabi', 0x77c4, 0x77ea),
                                ('power-callback-coprocessor-update', 'thumbv7-none-eabi', 0x7b2a, 0x7b58),
                                ('power-record-callback-entry', 'thumbv7-none-eabi', 0x857c, 0x85e2),
                                ('power-record-callback-body', 'thumbv7-none-eabi', 0x85e2, 0x87c6),
                                ('power-record-dispatch', 'thumbv7-none-eabi', 0x38024, 0x3821c),
                                ('power-record-transport-send', 'thumbv7-none-eabi', 0x384b8, 0x385ec),
                                ('startup-recovery-mode', 'thumbv7-none-eabi', 0x3004c, 0x3006c),
                                ('startup-worker-registration', 'thumbv7-none-eabi', 0xa780, 0xa7f2),
                                ('startup-worker-trampoline', 'thumbv7-none-eabi', 0xf7f0, 0xf876),
                                ('startup-host-write-state', 'thumbv7-none-eabi', 0xa8a0, 0xa8e2),
                                ('startup-final-schedule', 'thumbv7-none-eabi', 0xb000, 0xb01c),
                                ('startup-worker-release', 'thumbv7-none-eabi', 0x3b6e8, 0x3b718),
                                ('prenand-task-entry', 'thumbv7-none-eabi', 0x3b9ac, 0x3b9f4),
                                ('prenand-initialization-entry', 'thumbv7-none-eabi', 0x30f4c, 0x31318),
                                ('postnand-task-entry', 'thumbv7-none-eabi', 0x38e20, 0x38e56),
                                ('prenand-config-lookup', 'thumbv7-none-eabi', 0xbdd4, 0xbe12),
                                ('prenand-channel-compare', 'thumbv7-none-eabi', 0xdffc, 0xe026),
                                ('prenand-post-probe-queries', 'thumbv7-none-eabi', 0x313a0, 0x314f4),
                                ('prenand-before-query-checks', 'thumbv7-none-eabi', 0x30748, 0x30792),
                                ('anc-setting-7080', 'thumbv7-none-eabi', 0xbf58, 0xbf9a),
                                ('anc-setting-register-pair', 'thumbv7-none-eabi', 0xbfa0, 0xbfe6),
                                ('prenand-conditional-setting', 'thumbv7-none-eabi', 0x307c4, 0x30840),
                                ('prenand-setting-one', 'thumbv7-none-eabi', 0x3084c, 0x308a4),
                                ('prenand-setting-fallback', 'thumbv7-none-eabi', 0x308ac, 0x3094a),
                                ('anc-outgoing-setting', 'thumbv7-none-eabi', 0xb8c4, 0xbafe),
                                ('prenand-mapped-init-call', 'thumbv7-none-eabi', 0x31140, 0x31174),
                                ('prenand-mapped-init-entry', 'thumbv7-none-eabi', 0xd170, 0xd216),
                                ('prenand-resource-assignment', 'thumbv7-none-eabi', 0x31018, 0x31040),
                                ('prenand-bank-one-soc', 'thumbv7-none-eabi', 0xd216, 0xd252),
                                ('prenand-bank-zero-init', 'thumbv7-none-eabi', 0xd252, 0xd304),
                                ('prenand-bank-common-store', 'thumbv7-none-eabi', 0xd326, 0xd32a),
                                ('firmware-soc-parameter', 'thumbv7-none-eabi', 0xa530, 0xa548),
                                ('prenand-secondary-register-init', 'thumbv7-none-eabi', 0xd32a, 0xd418),
                                ('anc-register-defaults', 'thumbv7-none-eabi', 0xbcf8, 0xbdc0),
                                ('anc-init-polls-and-table', 'thumbv7-none-eabi', 0xd418, 0xd576),
                                ('anc-init-conditional-submit', 'thumbv7-none-eabi', 0x38980, 0x38a3c),
                                ('anc-reprobe-chip-id', 'thumbv7-none-eabi', 0xd700, 0xd7a2),
                                ('anc-read-result-bytes', 'thumbv7-none-eabi', 0xb764, 0xb7dc),
                                ('anc-reprobe-id-validation', 'thumbv7-none-eabi', 0xd7a2, 0xd8a2),
                                ('firmware-byte-compare', 'thumbv7-none-eabi', 0x16e8, 0x172c),
                                ('anc-reprobe-version-queries', 'thumbv7-none-eabi', 0xd8a6, 0xd9aa),
                                ('anc-reprobe-parameter-transfer', 'thumbv7-none-eabi', 0xd9aa, 0xdaee),
                                ('anc-pair-submit', 'thumbv7-none-eabi', 0x3886c, 0x38924),
                                ('anc-transfer-mode', 'thumbv7-none-eabi', 0x3876c, 0x38864),
                                ('anc-reprobe-parameter-validation', 'thumbv7-none-eabi', 0xdb68, 0xdc5e),
                                ('anc-reprobe-validation-tail', 'thumbv7-none-eabi', 0xdc5e, 0xdec4),
                                ('anc-reprobe-return-paths', 'thumbv7-none-eabi', 0xdedc, 0xdf64),
                                ('anc-query-entry', 'thumbv7-none-eabi', 0xc174, 0xc1f8),
                                ('anc-query-body', 'thumbv7-none-eabi', 0xc1f8, 0xc39a),
                                ('anc-query-status-decode', 'thumbv7-none-eabi', 0xb7ec, 0xb834),
                                ('anc-query-panic', 'thumbv7-none-eabi', 0xb83c, 0xb84c),
                                ('firmware-assert-dispatch', 'thumbv7-none-eabi', 0x27d6, 0x27fe),
                                ('firmware-panic-state', 'thumbv7-none-eabi', 0x2794, 0x27a6),
                                ('firmware-panic-loop', 'thumbv7-none-eabi', 0x9110, 0x9120),
                                ('firmware-panic-idle', 'thumbv7-none-eabi', 0x2fa0, 0x2fd2),
                                ('firmware-panic-report-entry', 'thumbv7-none-eabi', 0x9864, 0x98b2),
                                ('startup-platform-dispatch', 'thumbv7-none-eabi', 0x1e78, 0x1f1e),
                                ('startup-platform-resources', 'thumbv7-none-eabi', 0x1ffe, 0x20b0),
                                ('resource-map', 'thumbv7-none-eabi', 0x60b0, 0x60e6),
                                ('resource-map-wrapper', 'thumbv7-none-eabi', 0x6eac, 0x6ed6),
                                ('resource-map-body', 'thumbv7-none-eabi', 0x6edc, 0x7014)]:
    result = subprocess.run([str(bindir / 'llvm-objdump.exe'), '-d',
        '--triple=' + triple, '--mattr=+hwdiv', '--section=.data', '--start-address=' + str(start),
        '--stop-address=' + str(end), str(elf)], check=True, capture_output=True, text=True)
    target = OUT / ('ans-fw-' + name + '.txt')
    target.write_text(result.stdout, encoding='utf-8')
    reports.append(target.name)
markers = []
for match in re.finditer(rb'[ -~]{8,160}', raw):
    if re.search(rb'RTKit_iOS-|AppleStorageProcessorANS1-', match.group()):
        markers.append({'offset': hex(match.start()), 'text': match.group().decode('ascii')})
report = {'capture_sha256': expected, 'capture_bytes': len(raw),
    'physical_base': '0x87f600000', 'nonzero_bytes': sum(b != 0 for b in raw),
    'markers': markers,
    'bootstrap_literals': {hex(p): hex(struct.unpack_from('<I', raw, p)[0])
                           for p in range(0x438, 0x468, 4)},
    'startup_zeroing_literals': {hex(p): hex(struct.unpack_from('<I', raw, p)[0])
                                for p in range(0x2f24, 0x2f38, 4)},
    'startup_zeroing_parameter_payloads': {hex(p): raw[p+8:p+16].hex()
                                          for p in (0x4807d, 0x4808d)},
    'startup_init_array_bounds': [hex(struct.unpack_from('<I', raw, p)[0])
                                 for p in (0x2f90, 0x2f94, 0x2f98, 0x2f9c)],
    'startup_main_parameter_literals': {
        hex(p): hex(struct.unpack_from('<I', raw, p)[0])
        for p in (0xa7f4, 0xa7f8)},
    'startup_main_resource_literals': {
        hex(p): hex(struct.unpack_from('<I', raw, p)[0])
        for p in range(0xa7fc, 0xa814, 4)},
    'startup_main_task_array_bounds': [hex(struct.unpack_from('<I', raw, p)[0])
                                      for p in (0xa828, 0xa82c)],
    'startup_worker_table': {
        'registration_table_literal': hex(struct.unpack_from('<I', raw, 0xa868)[0]),
        'trampoline_literal': hex(struct.unpack_from('<I', raw, 0xa86c)[0]),
        'dispatch_table_literal': hex(struct.unpack_from('<I', raw, 0xf88c)[0]),
        'entries': [
            {'thumb_entry': hex(struct.unpack_from('<I', raw, 0x404d0 + i*12)[0]),
             'name': raw[struct.unpack_from('<I', raw, 0x404d4 + i*12)[0]:].split(b'\0', 1)[0].decode('ascii'),
             'stack_argument': hex(struct.unpack_from('<I', raw, 0x404d8 + i*12)[0])}
            for i in range(8)],
        'scope': 'Static registration and gated dispatch; task release conditions and NAND effects remain unproven'},
    'startup_worker_release': {
        'call_site': '0xb000', 'function': '0x3b6e8',
        'guard_object_literal': hex(struct.unpack_from('<I', raw, 0x3b718)[0]),
        'guard_offset': '0xe',
        'current_task_literal': hex(struct.unpack_from('<I', raw, 0x3b71c)[0]),
        'selector': '0x3b4e4', 'signal': '0x37c14', 'signal_object_offset': 4,
        'host_state_object_literal': hex(struct.unpack_from('<I', raw, 0xa8e4)[0]),
        'host_write_zero_halfword_store': '0xa8cc',
        'host_write_zero_offset': '0x9d',
        'scope': 'Conditional task selection and signal after initialization; no proof of firmware-wide write protection'},
    'nand_task_entry_paths': {
        'prenand': {'entry': '0x3b9ac', 'initial_call_site': '0x3b9ba',
                    'initialization': '0x30f4c',
                    'scope': 'Initialization is called before the request-state checks; downstream effects remain unresolved'},
        'postnand': {'entry': '0x38e20', 'setup_call': '0x9724',
                     'loop_calls': ['0x3b408', '0x38e6c', '0x38e6c'],
                     'object_literal': hex(struct.unpack_from('<I', raw, 0x38e68)[0]),
                     'second_object_offset': '0x744',
                     'scope': 'Entry and loop only; neither call is assumed to be write-free'}},
    'prenand_initialization_followup': {
        'lookup_function': '0xbdd4',
        'lookup_table_literal': hex(struct.unpack_from('<I', raw, 0xbe14)[0]),
        'lookup_count': 6, 'lookup_stride': '0x54',
        'lookup_input_key_offsets': ['0x48', '0x4c'],
        'mapped_init_call': '0x31168', 'mapped_init_function': '0xd170',
        'conditional_mapped_store_offsets': ['0x68', '0x6c', '0x70', '0x74', '0x78', '0x80', '0x7c'],
        'scope': 'Bounded lookup and conditional stores only; mapping identity and persistence effects unproven'},
    'prenand_resource_assignment': {
        'context_base_literal': hex(struct.unpack_from('<I', raw, 0x31328)[0]),
        'context_stride': '0x744', 'contexts': 2,
        'descriptor_literal': hex(struct.unpack_from('<I', raw, 0x31344)[0]),
        'assignment_site': '0x3103e', 'context_descriptor_offset': '0x10',
        'descriptor_physical_base_from_startup': '0x208081000',
        'descriptor_bytes_from_startup': '0x1000',
        'scope': 'Assignment linked to main startup descriptor setup; register semantics and persistence effects unresolved'},
    'prenand_t7000_bank_settings': {
        'soc_parameter_literal': hex(struct.unpack_from('<I', raw, 0xa548)[0]),
        'soc_parameter': '_COS', 'selected_soc': '0x7000',
        'base': '0x208081000',
        'context_zero': {'0x40': 2, '0x44': 2, '0x48': 2, '0x4c': 2,
                         '0x50': 0xff00, '0x58': 0xff00ff, '0x54': 5,
                         '0x60': 6, '0x64': 3},
        'context_one': {'0x68': 2, '0x6c': 2, '0x70': 2, '0x74': 2,
                        '0x78': 0xff00, '0x80': 0xff00ff, '0x7c': 5,
                        '0x88': 6, '0x8c': 3},
        'scope': 'Initial mapped stores only, not a complete initialization sequence or a payload to execute'},
    'prenand_secondary_descriptors': {
        'context_zero_descriptor': hex(struct.unpack_from('<I', raw, 0x3fd20)[0]),
        'context_one_descriptor': hex(struct.unpack_from('<I', raw, 0x3fd24)[0]),
        'context_descriptor_offset': '0xc',
        'physical_bases_from_main_setup': ['0x208800000', '0x208900000'],
        'bytes_per_region': '0x100000',
        'init_literal_at_d6c0': hex(struct.unpack_from('<I', raw, 0xd6c0)[0]),
        'init_literal_at_d6c4': hex(struct.unpack_from('<I', raw, 0xd6c4)[0]),
        'callback_object_literal': hex(struct.unpack_from('<I', raw, 0xd6d8)[0]),
        'callback_thumb_literal': hex(struct.unpack_from('<I', raw, 0xd6dc)[0]),
        'scope': 'Two additional register regions reached during initialization; register effects unresolved'},
    'anc_register_defaults': {
        'function': '0xbcf8', 'context_descriptor_offset': '0xc',
        'source_file': raw[struct.unpack_from('<I', raw, 0xbdcc)[0]:].split(b'\0', 1)[0].decode('ascii'),
        'mapping_assertion': raw[struct.unpack_from('<I', raw, 0xbdd0)[0]:].split(b'\0', 1)[0].decode('ascii'),
        'stores': {'0x201c': hex(struct.unpack_from('<I', raw, 0xbdc0)[0]),
                   '0x2018': '0xf0f', '0x2014': '0xe08',
                   '0x2010': hex(struct.unpack_from('<I', raw, 0xbdc4)[0]),
                   '0x2020': '0x0', '0x202c': '0x1', '0x2024': '0x0'},
        'scope': 'Complete bounded helper; register names and hardware effects are not inferred from constants'},
    'anc_initialization_tail': {
        'unbounded_bit_clear_polls': [
            {'offset': '0x2004', 'bit': 4, 'loop': ['0xd426', '0xd42a']},
            {'offset': '0x2004', 'bit': 7, 'loop': ['0xd442', '0xd446']},
            {'offset': '0x1004', 'bit': 2, 'loop': ['0xd45e', '0xd462']}],
        'template_literal': hex(struct.unpack_from('<I', raw, 0xd6e0)[0]),
        'template_words': [hex(struct.unpack_from('<I', raw,
            struct.unpack_from('<I', raw, 0xd6e0)[0] + i*4)[0]) for i in range(61)],
        'destination_offset': '0x3000', 'word_count': 61,
        'substitutions': 'Words matching mask 0x3f000000 == 0x38000000 use low16 index 0..5 to select configuration fields',
        'final_store': {'offset': '0x2000', 'value': 0},
        'scope': 'Static initialization sequence; no hardware effects or recovery guarantee inferred'},
    'anc_conditional_submit': {
        'function': '0x38980', 'init_call_site': '0xd4c8', 'init_value_argument': 0,
        'occupancy_context_offset': '0xac', 'occupancy_limit': '0x80',
        'occupancy_register_offset': '0x1c', 'occupancy_bits': [8, 15],
        'inhibit_byte_offset': '0xb1', 'value_register_offset': '0x140',
        'scope': 'Wait and conditional value submission, not a demonstrated stop or recovery operation'},
    'anc_reprobe_entry': {
        'function': '0xd700',
        'function_name': raw[struct.unpack_from('<I', raw, 0xdb00)[0]:].split(b'\0', 1)[0].decode('ascii'),
        'log_format': raw[struct.unpack_from('<I', raw, 0xdb08)[0]:].split(b'\0', 1)[0].decode('ascii'),
        'submit_thumb_literal': hex(struct.unpack_from('<I', raw, 0xdaf4)[0]),
        'initial_words': ['0x22000001', hex(struct.unpack_from('<I', raw, 0xdaf8)[0] + 0x19),
                          '0x12000000', 'configuration +0x38 with high byte 0x38',
                          hex(struct.unpack_from('<I', raw, 0xdafc)[0]), '0x22000000'],
        'read_helper': '0xb764', 'result_bytes': 6, 'context_result_offset': '0x1c',
        'status_offset': '0x24', 'status_mask': '0x7f00', 'data_offset': '0x1c0',
        'scope': 'Chip ID read phase only; remaining reprobe commands and side effects unverified'},
    'anc_reprobe_id_validation': {
        'manufacturer_address_word': hex(struct.unpack_from('<I', raw, 0xdb0c)[0]),
        'manufacturer_read_bytes': 6, 'manufacturer_context_offset': '0x22',
        'chip_id_prefix': raw[struct.unpack_from('<I', raw, 0xdb18)[0]:][:3].decode('ascii'),
        'prefix_compare_bytes': 3, 'prefix_mismatch_return': 5,
        'version_bytes': ['0x1f', '0x20', '0x21'],
        'missing_firmware_version': '0xffffff',
        'error_version': hex(struct.unpack_from('<I', raw, 0xdb20)[0]),
        'scope': 'Static rejection checks, not live probe evidence or complete reprobe safety'},
    'anc_reprobe_version_queries': {
        'version_threshold_literal': hex(struct.unpack_from('<I', raw, 0xdb2c)[0]),
        'maximum_version': hex(struct.unpack_from('<I', raw, 0xdb2c)[0] + 0xfb00),
        'unsupported_return': 4,
        'query_helper': '0xc174',
        'first_query': {'selector': '0xc080', 'bytes': 1},
        'conditional_queries': ['0xc280', '0xc180', '0xc380'],
        'firmware_version_query': {'selector': '0x9080', 'bytes': 16, 'context_offset': '0x28'},
        'version_log': raw[struct.unpack_from('<I', raw, 0xdb3c)[0]:].split(b'\0', 1)[0].decode('ascii'),
        'scope': 'Observed call arguments; full query helper side effects remain unverified'},
    'anc_reprobe_parameter_transfer': {
        'entry': '0xd9aa',
        'trace_labels': [raw[struct.unpack_from('<I', raw, p)[0]:].split(b'\0', 1)[0].decode('ascii')
                         for p in (0xdb48, 0xdb5c)],
        'command_literals': {hex(p): hex(struct.unpack_from('<I', raw, p)[0])
                             for p in (0xdaf0, 0xdaf8, 0xdb4c, 0xdb50, 0xdb54, 0xdb58)},
        'descriptor_table_literal': hex(struct.unpack_from('<I', raw, 0xdb44)[0]),
        'descriptor_stride': 8,
        'pair_calls': ['0xda7e', '0xda8a'],
        'pair_helper': '0x3886c',
        'pair_register_offset': '0x100',
        'pair_stores': ['0x388e4', '0x388f2'],
        'pair_queue_count_offset': '0xa8',
        'pair_queue_full_at': 64,
        'pair_count_refresh': 'mapped +0x18 bits 8..14',
        'completion_wait': '0xda8e..0xda98 waits for context +0x108 to become zero, yielding through 0x3b574',
        'completion_wait_timeout': None,
        'first_parameter_checks': [
            {'offset': '0x10', 'min': 1, 'max': 64,
             'label': raw[struct.unpack_from('<I', raw, 0xdb60)[0]:].split(b'\0', 1)[0].decode('ascii')},
            {'offset': '0x14', 'min': 1, 'max': 7,
             'label': raw[struct.unpack_from('<I', raw, 0xdb64)[0]:].split(b'\0', 1)[0].decode('ascii')}],
        'scope': 'Static startup submissions and parameter checks; wire semantics, persistent effects and complete startup read-only behavior remain unverified'},
    'prenand_outgoing_settings': {
        'helper': '0xb8c4',
        'trace_label': raw[struct.unpack_from('<I', raw, 0xbb1c)[0]:].split(b'\0', 1)[0].decode('ascii'),
        'startup_calls': [
            {'site': '0x3080a', 'selector': '0x7180', 'bytes': 4, 'payload_u32': 0,
             'condition': 'caller 0x313c0 plus context bytes +0x38 and +0x628 nonzero'},
            {'site': '0x30884', 'selector': '0x480', 'bytes': 4, 'payload_u32': 1,
             'condition': '0x314de reached after successful post-probe query loop'}],
        'ordinary_path': 'For these non-0x380 selectors, b9fc loads caller payload words and ba00 sends them via 0x38980',
        'synchronous_wait': '0xba8a..0xba94 waits for context +0x108 to clear without a timeout',
        'response': 'reads one status byte through 0xb764 then decodes it through 0xb7ec',
        'scope': 'Outgoing payload direction proven; feature meanings and persistence remain unknown. This is not a read-only query path.'},
    'prenand_setting_flag_origin': {
        'fresh_context_guard': '0x30fc8 tests context byte +4; zero enters initialization',
        'value_definition': '0x30fd0 sets r5 to 1',
        'store': '0x31006 stores halfword 1 at context +0x628',
        'result_bytes': {'0x628': 1, '0x629': 0},
        'version_guard': '0xd8d4 sets context +0x38 when Chip ID version exceeds 0x104ff',
        'scope': 'Fresh initialization defaults, not a retained-state observation or proof that no later writer changes the flag'},
    'prenand_setting_7080': {
        'caller': '0x3077a', 'helper': '0xbf58',
        'condition': 'context bytes +0x38 and +0x628 both nonzero',
        'setting_call': '0xbf6c', 'selector': '0x7080', 'bytes': 4, 'payload_u32': 1,
        'success': {'cached_byte': 'context +0x114', 'register_helper': '0xbfa0',
                    'mapped_register_offset': '0x2000', 'operation': 'read-modify-write setting bit 1'},
        'failure': 'returns false without calling the register helper',
        'scope': 'Proven outgoing setting plus paired register change; feature semantics and persistence unverified'},
    'prenand_setting_fallback': {
        'caller': '0x314e8', 'helper': '0x308ac',
        'first': {'site': '0x308e8', 'selector': '0x8580', 'payload_u32': 1, 'bytes': 4},
        'fallback': {'site': '0x30902', 'selector': '0xb080', 'payload_u32': 1, 'bytes': 4,
                     'condition': 'first call returns nonzero'},
        'success_state': {'context_offset': '0x3c', 'value': 1},
        'both_failed_state': 'context +0x3c becomes 2 if manufacturer byte +0x22 is 0x98, otherwise 0',
        'scope': 'Additional outgoing startup settings; feature meanings and persistence not established. No hardware execution.'},
    'prenand_channel_comparison': {
        'call': '0x312ce', 'helper': '0xdffc',
        'comparisons': [{'context_offset': '0x1c', 'bytes': 6},
                        {'context_offset': '0x28', 'bytes': 16}],
        'compare_helper': '0x16e8',
        'result': '0 if both ranges match, otherwise 1',
        'caller_mismatch_status': {'site': '0x312de', 'offset': '0x264', 'value': 7},
        'scope': 'RAM byte comparisons only; this helper has no controller access'},
    'prenand_post_probe_queries': {
        'helper': '0xc174',
        'fixed': [{'site': '0x31438', 'selector': '0x85', 'bytes': 10,
                   'condition': 'context byte +0x38 nonzero'},
                  {'site': '0x31462', 'selector': '0xa180', 'bytes': 16},
                  {'site': '0x31476', 'selector': '0xa080', 'bytes': 16},
                  {'site': '0x3148a', 'selector': '0xa181', 'bytes': 16}],
        'indexed': {'site': '0x314b4', 'selector': '(index << 8) + 0x82, truncated to u16',
                    'bytes': 16, 'bound': 'selected parameter word +0x38'},
        'scope': 'Observed call arguments only; selector semantics are unverified and these calls have not been executed on hardware'},
    'anc_reprobe_transfer_mode': {
        'call': '0xda0c', 'helper': '0x3876c',
        'arguments_after_context': [0, 0, 0, 0, 0],
        'cached_fields': ['context +0xe0 (word)', 'context +0xe4 (byte)'],
        'cached_zero_path': '0x387c8 -> 0x387ca -> 0x38810 returns without submission',
        'changed_path': 'stores zero in both cached fields and submits [0, 0x200000] twice through 0x3886c',
        'nonzero_third_argument_path': '0x387d0..0x38860 not reached by this caller; contains additional buffer submissions',
        'scope': 'Caller-specific control flow; the hardware meaning of 0x200000 remains unverified'},
    'anc_reprobe_validation_exit': {
        'validator_label': raw[struct.unpack_from('<I', raw, 0xdf6c)[0]:].split(b'\0', 1)[0].decode('ascii'),
        'failure_format': raw[struct.unpack_from('<I', raw, 0xdfec)[0]:].split(b'\0', 1)[0].decode('ascii'),
        'validation_failure': {'log': '0xdd1e', 'return_value': 3, 'branch': '0xdd24'},
        'success': {'store_site': '0xdf26', 'context_offset': '0x64',
                    'value': 'parameter word +0x34 divided by context word +0x60',
                    'return_value': 0, 'branch': '0xdf2c'},
        'shared_return': '0xd84c',
        'transfer_helper_failure': {'branches': ['0xddda', '0xdde2'],
                                    'panic_call': '0xddea -> 0x27d6'},
        'scope': 'Validation and return paths following transfer, not proof that the transfer or earlier startup phases avoid persistent writes'},
    'anc_query_response_path': {
        'special_dma_condition': 'selector == 0x380 and requested bytes > 0x100',
        'ordinary_status_read': {'call': '0xc32c', 'bytes': 1},
        'ordinary_payload_read': '0xc336',
        'state_clear': {'site': '0xc33c', 'context_offset': '0x108'},
        'status_decoder': '0xb7ec',
        'special_error_codes': ['0x50', '0x51'], 'special_error_result': 5,
        'special_error_call': '0xb83c',
        'scope': 'Response flow only; submitted selector semantics and error-handler effects remain unresolved'},
    'anc_query_panic_path': {
        'message': raw[struct.unpack_from('<I', raw, 0xb84c)[0]:].split(b'\0', 1)[0].decode('ascii'),
        'calls': ['0xb83c', '0x27d6', '0x2794', '0x9110'],
        'state_word_literal': hex(struct.unpack_from('<I', raw, 0x27a8)[0]),
        'state_value': 4, 'loop_call': '0x2fa0', 'loop_branch': '0x911e',
        'scope': 'Interrupt-disabled non-returning path; DMA quiescence and complete panic side effects unproven'},
    'firmware_panic_idle': {
        'function': '0x2fa0',
        'flag_object_literal': hex(struct.unpack_from('<I', raw, 0x2fd4)[0]),
        'flag_offset': 1, 'wait_instructions': ['0x2faa', '0x2fc6'],
        'nonzero_flag_path': 'Temporarily clears bit 2 of CP15 c1,c0,0 around WFI and restores it',
        'scope': 'CPU idle only; no peripheral DMA-stop operation in this bounded function'},
    'captured_power_task_not_boot_state': {
        'name_literal': hex(struct.unpack_from('<I', raw, 0xa818)[0]),
        'entry_thumb_literal': hex(struct.unpack_from('<I', raw, 0xa81c)[0]),
        'context_literal': hex(struct.unpack_from('<I', raw, 0xa810)[0]),
        'context_words': {hex(p): hex(struct.unpack_from('<I', raw, p)[0])
                          for p in range(0x4c650, 0x4c6a0, 4)},
        'callback_records': [[hex(v) for v in struct.unpack_from('<III', raw, power_table + i * 12)]
                             for i in range(power_count)],
        'callback_dispatch_sites': ['0x92e8', '0x9308', '0x9322'],
        'scope': 'Saved task context only; callback registration and post-start state are not inferred'},
    'power_callback_registration': {
        'map_function': '0x78c0',
        'success_path_flag_load': '0x798c',
        'flag_bit': 9,
        'conditional_store': '0x7998',
        'object_literal': hex(struct.unpack_from('<I', raw, 0x79b8)[0]),
        'callback_literal': hex(struct.unpack_from('<I', raw, 0x79bc)[0]),
        'destination_offset': '0x44',
        'observed_caller': '0x84fe',
        'caller_stack_flags': '0x200',
        'scope': 'One confirmed registration path; not exhaustive callers or startup reachability'},
    'power_callback_downstream': {
        'reference_count_literal': hex(struct.unpack_from('<I', raw, 0x77ec)[0]),
        'callback_reference_count_literal': hex(struct.unpack_from('<I', raw, 0x78b8)[0]),
        'acquire': '0x77c4',
        'first_reference_calls': {'function': '0x7b2a', 'r0': 1},
        'last_release_calls': {'function': '0x7b2a', 'r0': 0},
        'coprocessor_update_window': ['0x7b2a', '0x7b58'],
        'scope': 'Bounded normal path updates a RAM count and CP15 registers; this does not cover other task callbacks or firmware startup'},
    'captured_power_record_dispatch': {
        'context': '0x4c0e4',
        'selector_at_context_a8': hex(struct.unpack_from('<I', raw, 0x4c18c)[0]),
        'ring_at_context_84': hex(struct.unpack_from('<I', raw, 0x4c168)[0]),
        'dispatch_function': '0x38024',
        'registry_literal': hex(struct.unpack_from('<I', raw, 0x38228)[0]),
        'buffer_response_wait': ['0x871a', '0x872e'],
        'pending_item_loop': ['0x8786', '0x87b0'],
        'indirect_call_site': '0x381f2',
        'scope': 'Captured selector and bounded instruction paths; destination effects and startup reachability remain unproven'},
    'captured_power_transport': {
        'registry_entry': hex(struct.unpack_from('<I', raw, 0x4c5e4)[0]),
        'transport_object': hex(struct.unpack_from('<I', raw, 0x700fc)[0]),
        'vtable': hex(struct.unpack_from('<I', raw, 0x4c23c)[0]),
        'send_thumb': hex(struct.unpack_from('<I', raw, 0x47b18)[0]),
        'mapped_base': hex(struct.unpack_from('<I', raw, 0x4c240)[0]),
        'control_offset': hex(struct.unpack_from('<I', raw, 0x4c2bc)[0]),
        'data_offset': hex(struct.unpack_from('<I', raw, 0x4c2c0)[0]),
        'full_bit': 16,
        'payload_store_site': '0x385ba',
        'scope': 'Captured pointer chain and firmware-side send path; mapped addresses are not host physical addresses'},
    'startup_main_control_flow': {
        'heap_parameters': ['0BHR', '0SHR'],
        'nonzero_heap_branch': '0xa69a',
        'heap_mapping_call': '0x7018',
        'both_heap_mapping_outcomes_join': '0xa58c',
        'resource_map_helper': '0x60b0',
        'subsequent_resource_descriptors': [
            {'object': '0xd0680', 'physical': '0x208081000', 'bytes': '0x1000'},
            {'object': '0xd0658', 'physical': '0x208800000', 'bytes': '0x100000'},
            {'object': '0xd066c', 'physical': '0x208900000', 'bytes': '0x100000'}],
        'scope': 'Static branch and descriptor setup only; mapping internals and downstream startup side effects remain unproven'},
    'clog_readonly_string_offset': '0x41f8b',
    'clog_readonly_literal_references': [hex(p) for p in range(0, len(raw)-3, 4)
        if struct.unpack_from('<I', raw, p)[0] == 0x41f8b],
    'event_word_address_literal': hex(struct.unpack_from('<I', raw, 0x10c40)[0]),
    'event_word_literal_references_in_code_region': [hex(p) for p in range(0, 0x48000, 4)
        if struct.unpack_from('<I', raw, p)[0] == 0xec74c],
    'task_table_first_eight_entries': [[hex(v) for v in struct.unpack_from('<III', raw, 0xec6e4 + i*12)]
                                      for i in range(8)],
    'read_write_dispatch_targets': {hex(0x10+i): hex(0x3cfa8 + 2*struct.unpack_from('<H', raw, 0x3cfa8+2*i)[0])
                                    for i in range(4)},
    'writable_state_object_literal': hex(struct.unpack_from('<I', raw, 0x3d1b8)[0]),
    'command_pointer_table': '0xc9828',
    'captured_identify_inputs_not_live_response': {
        'pages_at_0x7e040': struct.unpack_from('<I', raw, 0x7e040)[0],
        'page_bytes_from_instruction': 4096,
        'preferred_factors_at_0x95b8c_0x95b94': [struct.unpack_from('<I', raw, p)[0] for p in (0x95b8c, 0x95b94)],
        'formatted_byte_at_0x78f54': raw[0x78f54],
        'pending_source_word_at_0xd65d4': struct.unpack_from('<I', raw, 0xd65d4)[0],
        'mode_at_0x95bb0': struct.unpack_from('<I', raw, 0x95bb0)[0],
        'util_default_source_at_0x7e030': struct.unpack_from('<I', raw, 0x7e030)[0],
        'util_mode3_source_at_0xdc24c': raw[0xdc24c]},
    'internal_identify_dispatch_target': hex(0x18352 + 2*struct.unpack_from('<H', raw, 0x18352 + 2*(0x1b-1))[0]),
    'internal_enable_write_dispatch_target': hex(0x18352 + 2*struct.unpack_from('<H', raw, 0x18352 + 2*(0x1f-1))[0]),
    'captured_writable_byte_at_0xd65e9': raw[0xd65e9],
    'captured_allocator_wait_mask_at_0xf0778': struct.unpack_from('<I', raw, 0xf0778)[0],
    'allocator_current_task_pointer_literal': hex(struct.unpack_from('<I', raw, 0x32c50)[0]),
    'captured_background_inputs_not_boot_state': {
        'state_at_0xdc1f0': struct.unpack_from('<I', raw, 0xdc1f0)[0],
        'pending_at_0x95d68': struct.unpack_from('<I', raw, 0x95d68)[0],
        'guard_at_0xd05b0': raw[0xd05b0],
        'selector_at_0xdb3a6': raw[0xdb3a6],
        'enabled_at_0xdc24c': raw[0xdc24c]},
    'command_pointer_table_literal_references': [hex(p) for p in range(0, 0x3fd00, 4)
        if struct.unpack_from('<I', raw, p)[0] == 0xc9828],
    'disassembly_files': reports,
    'scope': 'Static captured-image analysis; not proof of write-free startup or firmware integrity'}
(OUT / 'ans-fw-analysis.json').write_text(json.dumps(report, indent=2), encoding='utf-8')
print(json.dumps(report, indent=2))
